### ISSUE TITLE
Scheduling

### ISSUE THREAD

**Issue by abattye** [sapcc/asr1k-neutron-l3#11]
Take some care on the existing (essentially noop) scheduler. Initially target a least used strategy and consider manual/automatic rescheduling

**Comment by lzachery** [comment]
Assume this is in relation to multiple ASR pairs?

**Comment by abattye** [comment]
Yes - everythiung is currently only tested on one pair with a noop scheduler. I need to refactor the handling of the pair configuration (and also prepare our helm charts for this) before we can test horizontal scale out
