### ISSUE TITLE
NCclient session_close blocks eventlet threads

### ISSUE THREAD

**Issue by abattye** [sapcc/asr1k-neutron-l3#12]
The workaround to some Yang issues is currently to fallback to legacy Netconf configuration. Due to (apparent) issues with visibility of configuration changes on devices through different sessions we tried to ensure legacy netconf SSH session were closed immediately after use. This seems to conflict with the latest ncclient/paramiko releases when opening/closing sessions from Eventlet Greenthreads. Its seems to block threads which never yield.

**Comment by einarnn** [comment]
Andrew,

There was a recent PR accepted into ncclient that _may_ impact this issue:

> https://github.com/ncclient/ncclient/issues/214

I'm not saying it is necessarily the same issue, but if you are willing to try out that version of ncclient (which hasn't been tagged and uploaded to PyPi as yet), then you could try (in your python virtualenv):

```
pip install --upgrade git+https://github.com/ncclient/ncclient.git
```

...and see if it has any impact this issue.

Cheers,

Einar

**Comment by abattye** [comment]
The above makes no difference to the beahviour. Currently testing a workaround of closing directory on the transport layer https://github.com/sapcc/asr1k-neutron-l3/blob/master/asr1k_neutron_l3/models/netconf.py#L160

**Comment by abattye** [comment]
This issue is caused by this : 

https://github.com/ncclient/ncclient/blob/master/ncclient/transport/ssh.py#L316-L317

It appears the while condition is not valid when using greenlets

**Comment by abattye** [comment]
Fixed with a patch to ncclient to prevent blocking
