### ISSUE TITLE
Platform related failures on some configurations

### ISSUE THREAD

**Issue by lzachery** [sapcc/asr1k-neutron-l3#17]
In some configurations ping/reachability failures are seen.  This is due to platform config support issue sin some use cases.  The problematic sue case is one in which on service in a VM is trying to reach another service in the same VM.

**Comment by abattye** [comment]
Its not BD configuration its platform support.

**Comment by lzachery** [comment]
Thanks for the comment Andrew - I fixed the description.

**Comment by abattye** [comment]
Workaround provided, and work towards a full solution is ongloing with Cisco
