### ISSUE TITLE
Set 'no shutdown' via Netconf Yang model

### ISSUE THREAD

**Issue by abattye** [sapcc/asr1k-neutron-l3#5]
It seems currently we can't `no shut` a BDI interface by sending a replace operation model without the shutdown element set. Needs further investigation and/or comment from Cisco.Only workaround if this is the case is to resort to Netconf legacy

**Comment by abattye** [comment]
So some further testing shows that if an interface is not existing a netconf create or replace will always create the interface in the default state of shutdown. Even if you omit the `<shutdown` element in the config body. 

It possible to `no shut` the interface by doing the following :

1. Create the interface using create/replace operation > interface is shutdown
2. Update the interface with a replace operation including <shutdown/> element > interface is still shutdown
3. Update the interface with a replace operation omitting <shutdown/> element > interface is up

Desired behaviour is that the inclusion or omission of the <shutdown/> element is honoured in the first call to create the interface.

**Comment by abattye** [comment]
This works when issuing two model updates, however it appears that unless the shutdown element is part of the model update (rather than being omitted and the shutdown state being implied) then subsequent updates without a shutdown element will not change the interface state

**Comment by einarnn** [comment]
Yes, that appears to be the case. I was able to get the two-step operation to work by explicitly provisioning the interface in a shutdown state. Below is what I suspect you are doing. First operation:

```
<config>
  <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
    <interface>
      <BDI>
        <name>{{NAME}}</name>
        <description>{{DESCR}}</description>
        <shutdown/>
      </BDI>
    </interface>
  </native>
</config>
```

Followed by:

```
<config>
  <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
    <interface>
      <BDI>
        <name>{{NAME}}</name>
        <shutdown operation="delete"/>
      </BDI>
    </interface>
  </native>
</config>
```

I will be raising an internal trouble ticket to reflect the incorrect config state after creating the BDI interface. Hopefully the workaround you have found will suffice for now.

Cheers,

Einar

**Comment by abattye** [comment]
Reverted back to netconf legacy approach to set `no shutdown` for now , using the two operations was not always reliable

**Comment by abattye** [comment]
Fixed in new device firmware
