### ISSUE TITLE
Route Map yang 'get' returns no data

### ISSUE THREAD

**Issue by abattye** [sapcc/asr1k-neutron-l3#6]
Retrieving a Route Map via netconf yang appears to yield no data. 

We have device configuration shown via CLI

     router1#show run | sect route-map
     route-map exp-beae927f77b04f6e9c00265d999e9c04 permit 10 
          match ip address prefix-list snat-beae927f77b04f6e9c00265d999e9c04
          set extcommunity rt 65891:141 additive
     route-map exp-beae927f77b04f6e9c00265d999e9c04 deny 20 
          match ip address prefix-list exp-beae927f77b04f6e9c00265d999e9c04

Issuing the following via either ncclient or Yang explorer

     <rpc message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
        <get>
           <filter>
             <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                 <route-map/>
             </native>
          </filter>
       </get>
     </rpc>

yields this result 

       <rpc-reply message-id="urn:uuid:13576a20-7cee-49a4-a89f-8807e0f97ad6" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
          <data/>
       </rpc-reply>

**Comment by abattye** [comment]
Have seen similar behaviour just now with access-list which could be solved by ensuring the ios-acl namespace is applied to all filter elements below 'extended'. This requirement seems somewhat inconsistent with other models not requiring the namespace. I think though that the above is not 100% reproducible and falls into the same category are the RD on VRFs where the Yang layer is introducing some inconsistency.

**Comment by martink2** [comment]
No longer an issue in latest fw
