### ISSUE TITLE
Problems manipulating RD on VRF

### ISSUE THREAD

**Issue by abattye** [sapcc/asr1k-neutron-l3#7]
There are several issues removing the RD config from a VRF when using Netconf Yang. The first is using Yang directly. Where a config request like this 

    <rpc message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
       <edit-config>
           <target>
             <running/>
           </target>
           <config>
             <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
               <vrf operation="replace">
                        <definition>
                                <name>beae927f77b04f6e9c00265d999e9c04</name>
                                <description>beae927f-77b0-4f6e-9c00-265d999e9c04</description>
                                <address-family>
                                       <ipv4></ipv4>
                                </address-family>
                        </definition>
            </vrf>
          </native>
        </config>
      </edit-config>
      <commit/>
    </rpc>

against device configuration 

    vrf definition beae927f77b04f6e9c00265d999e9c04
     description beae927f-77b0-4f6e-9c00-265d999e9c04
     rd 65192:1
     !
     address-family ipv4
      export map exp-beae927f77b04f6e9c00265d999e9c04
     exit-address-family

Results in 

     <nc:rpc-error xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
       <nc:error-type>application</nc:error-type>
       <nc:error-tag>invalid-value</nc:error-tag>
       <nc:error-severity>error</nc:error-severity>
       <nc:error-message lang="en" xmlns="http://www.w3.org/XML/1998/namespace">inconsistent value: Device refused one or more commands</nc:error-message>
       <nc:error-info>
         <severity xmlns="http://cisco.com/yang/cisco-ia">error_cli</severity>
         <detail xmlns="http://cisco.com/yang/cisco-ia">
           <bad-cli>
             <bad-command>no vrf definition Mgmt-intf</bad-command>
             <error-location>7</error-location>
           </bad-cli>
           <bad-cli>
             <bad-command>no export map exp-beae927f77b04f6e9c00265d999e9c04</bad-command>
             <error-location>12</error-location>
           </bad-cli>
         </detail>
       </nc:error-info>
     </nc:rpc-error>

As a workaround trying to using the CLI or netconf legacy to remove the RD appears to work and the CLI reports 

    vrf definition beae927f77b04f6e9c00265d999e9c04
     description beae927f-77b0-4f6e-9c00-265d999e9c04
     !
     address-family ipv4
     exit-address-family
    !

But from Yang we get :

    <rpc-reply message-id="urn:uuid:3dc6c826-47da-44ed-a3de-04d4e32644d8" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
      <data>
        <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
          <vrf>
            <definition>
              <name>beae927f77b04f6e9c00265d999e9c04</name>
              <description>beae927f-77b0-4f6e-9c00-265d999e9c04</description>
              <rd>65192:1</rd>
              <address-family>
                <ipv4>
                  <export>
                    <map>exp-beae927f77b04f6e9c00265d999e9c04</map>
                  </export>
                </ipv4>
              </address-family>
            </definition>
          </vrf>
        </native>
      </data>
    </rpc-reply>

And because Yang still sees the RD set any attempt to reconfigure the VRF without the RD or export fails.

**Comment by abattye** [comment]
As a workaround for now add RD for all VRFs and remove when VRF (i.e. Neutron router) is deleted. 

Impact is that probably 80-90% of routers will have unnecessary confg and teardown of these routers will take extra time (leading to more probability of errord)

**Comment by einarnn** [comment]
As discussed on the call we had, please try using:

```
<rpc message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
   <edit-config>
       <target>
         <running/>
       </target>
       <config>
         <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
           <vrf>
                    <definition operation="replace">
                            <name>beae927f77b04f6e9c00265d999e9c04</name>
                            <description>beae927f-77b0-4f6e-9c00-265d999e9c04</description>
                            <address-family>
                                   <ipv4></ipv4>
                            </address-family>
                    </definition>
        </vrf>
      </native>
    </config>
  </edit-config>
  <commit/>
</rpc>
```

**Comment by abattye** [comment]
I still can't find a way to get this working, move the operation removes `<bad-command>no vrf definition Mgmt-intf</bad-command>` but the error for `<bad-command>no export map exp-beae927f77b04f6e9c00265d999e9c04</bad-command>` remains. 

It looks like we can workaround (or maybe this is 'works as designed') but supplying the original route map export, the implication I think being that the address family section is processed before the RD, so we get an error if the export is removed and the RD element is present, but if we leave the export and then just remove the RD there is a cascading delete of the export. Testing continues

**Comment by einarnn** [comment]
Ok, what is happening here is the removing the RD has the side-effect of removing the command `export map exp-beae927f77b04f6e9c00265d999e9c04` from the IPv4 address family config. However, netconf is expecting to remove the export map command, which is no longer there, and so it fails. I'll raise an internal trouble ticket.
