### ISSUE TITLE
Handle device unavailability

### ISSUE THREAD

**Issue by abattye** [sapcc/asr1k-neutron-l3#8]
Rework device configuration and shorten time out, with back off/device status handling. Consider device specific sync.

**Comment by lzachery** [comment]
two details around this:
1) some intermittent connectivity issues cause significant syncing activity in the plugin 
2) some cleanup of connectivity checking may be causing issues

**Comment by abattye** [comment]
Initial, basic implementation https://github.com/sapcc/asr1k-neutron-l3/commit/d009df0cc316ff2d07a6079cb2b9424ea4f1a71b in testing
